# Generated by Django 3.2 on 2021-04-17 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=32)),
                ('eng_code', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driv_full_name', models.CharField(max_length=32)),
                ('driv_eng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eng_driv', to='engins.engin')),
                ('driv_eng_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eng_driv_code', to='engins.engin')),
            ],
        ),
    ]
