# Generated by Django 3.2 on 2021-04-17 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driv_full_name', models.CharField(max_length=32)),
                ('driv_eng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engins.engin')),
            ],
        ),
    ]
